# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "project_messaging_application_message_layer"
version = "0.1.0"
edition = "2018"
description = "Messaging Layer for Toy messaging application"

[dependencies]
sha2 = "0.9"